/* eslint-disable */
require('./add_font')
require('./decrease')
require('./download')
require('./increase')
require('./lowercase')
require('./move')
require('./rotate')
require('./type-filled')
require('./type')
